blank_issues_enabled: true
contact_links:
  - name: 💬 Discord Community
    url: https://discord.gg/ExkyhBny
    about: Join our Discord for questions, discussions, and community support
  - name: 💡 GitHub Discussions
    url: https://github.com/AEtherlight-ai/lumina/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Vulnerability
    url: https://github.com/AEtherlight-ai/lumina/security/policy
    about: Report security vulnerabilities privately to security@aetherlight.ai
