/**
 * Install Git Hooks for Task Document Validation
 *
 * Usage: node scripts/install-hooks.js
 */

const fs = require('fs');
const path = require('path');

const PRE_COMMIT_HOOK = `#!/bin/bash
# Pre-commit hook: Validate task document links
# Generated by scripts/install-hooks.js (Pattern-DOCS-002)

echo "🔍 Validating task document links..."
node scripts/validate-task-docs.js

if [ $? -ne 0 ]; then
  echo ""
  echo "❌ Task document validation failed!"
  echo "Fix errors above or use --no-verify to skip (NOT RECOMMENDED)"
  exit 1
fi

echo "✅ Task document validation passed"
`;

const hookPath = path.join('.git', 'hooks', 'pre-commit');

// Check if .git directory exists
if (!fs.existsSync('.git')) {
  console.error('❌ Error: .git directory not found. Is this a git repository?');
  process.exit(1);
}

// Check if hooks directory exists
if (!fs.existsSync(path.join('.git', 'hooks'))) {
  fs.mkdirSync(path.join('.git', 'hooks'), { recursive: true });
}

// Write hook
fs.writeFileSync(hookPath, PRE_COMMIT_HOOK, { mode: 0o755 });

console.log('✅ Pre-commit hook installed:', hookPath);
console.log('\nThe hook will run automatically before every commit.');
console.log('To bypass (emergency only): git commit --no-verify');
