name: Build Native Bindings

on:
  push:
    branches: [master, main]
    paths:
      - 'packages/aetherlight-node/**'
      - 'crates/**'
      - '.github/workflows/build-native-bindings.yml'
  pull_request:
    paths:
      - 'packages/aetherlight-node/**'
      - 'crates/**'
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to npm after build'
        required: false
        default: 'false'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            build: npm run build

          - host: windows-latest
            target: aarch64-pc-windows-msvc
            build: npm run build -- --target aarch64-pc-windows-msvc

          - host: macos-13
            target: x86_64-apple-darwin
            build: npm run build

          - host: macos-14
            target: aarch64-apple-darwin
            build: npm run build

          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: npm run build

          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build: |
              sudo apt-get update
              sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
              npm run build -- --target aarch64-unknown-linux-gnu

    name: Build ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ matrix.settings.target }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ matrix.settings.target }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        working-directory: packages/aetherlight-node
        run: npm install

      - name: Build native bindings
        working-directory: packages/aetherlight-node
        run: ${{ matrix.settings.build }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: packages/aetherlight-node/*.node
          if-no-files-found: error

  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages/aetherlight-node/artifacts

      - name: Move binaries to package root
        working-directory: packages/aetherlight-node
        run: |
          for dir in artifacts/bindings-*; do
            cp $dir/*.node . 2>/dev/null || true
          done
          ls -la *.node

      - name: Install dependencies
        working-directory: packages/aetherlight-node
        run: npm install

      - name: Publish to npm
        working-directory: packages/aetherlight-node
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
